"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, BatteryFull, Brain, ChevronDown, Clock3, HeartPulse, Menu, MessageCircle, Moon, Play, Sparkles, TrendingUp, X, Zap } from "lucide-react";
import type { PhotoReview, VideoReview } from "@/data/reviews";
import { whatsappHref } from "@/config/site";

const nav = [ ["产品介绍", "#benefits"], ["核心成分", "#ingredients"], ["食用方式", "#how-to-use"], ["顾客反馈", "#reviews"], ["FAQ", "#faq"] ];
function BrandLogo() { return <span className="brand-logo"><Image src="/brand/better-man-logo.png" alt="Better Man 官方 Logo" width={1391} height={970} priority /></span>; }
function WaButton({ children = "WhatsApp 咨询", light = false, className = "" }: { children?: React.ReactNode; light?: boolean; className?: string }) { return <a className={`button button-whatsapp ${light ? "button-whatsapp-light" : ""} ${className}`} href={whatsappHref()} target="_blank" rel="noopener noreferrer" aria-label="通过 WhatsApp 咨询 Better Man"><MessageCircle size={18}/>{children}<ArrowUpRight size={17}/></a>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
function SectionHeading({ eyebrow, title, desc, center = false }: { eyebrow: string; title: React.ReactNode; desc?: React.ReactNode; center?: boolean }) { return <div className={`section-heading ${center ? "center" : ""}`}><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{desc && <p className="section-desc">{desc}</p>}</div>; }
function Header() { const [open, setOpen] = useState(false); return <header className="site-header"><div className="container header-inner"><a className="brand" href="#home" aria-label="Better Man 首页"><BrandLogo/></a><nav className="desktop-nav" aria-label="主导航">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><WaButton className="header-cta">WhatsApp 咨询</WaButton><button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-nav" aria-label={open ? "关闭菜单" : "打开菜单"}>{open ? <X/> : <Menu/>}</button></div>{open && <nav id="mobile-nav" className="mobile-nav" aria-label="移动导航"><a className="mobile-brand" href="#home" onClick={() => setOpen(false)}><BrandLogo/></a>{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}<ArrowUpRight size={16}/></a>)}<WaButton>WhatsApp 立即咨询</WaButton></nav>}</header>; }
function Hero() { return <section id="home" className="hero"><div className="container hero-grid"><div className="hero-copy"><Eyebrow>BETTER MAN / 男性日常状态保养</Eyebrow><h1>不够硬、撑不久、<br/><em>状态越来越难维持？</em></h1><p className="hero-value">把精神、体力、耐力与男性状态，放回日常慢慢照顾。</p><p className="hero-quick-info">Better Man 男性日常保养<span>｜</span>5天1颗<span>｜</span>一盒14颗</p><div className="hero-primary-action"><WaButton>WhatsApp 私下了解</WaButton><small>一对一咨询 · 不清楚怎么吃可以直接问</small></div></div><div className="hero-visual"><div className="hero-art"><div className="hero-product"><Image src="/images/hero/better-man-product.png" alt="Better Man 宝马糖产品盒与独立包装" width={1254} height={1254} priority className="product-image" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 900px) min(620px, calc(100vw - 48px)), 45vw"/></div></div><div className="hero-product-points" aria-label="Better Man 产品快速资料"><div><strong>5天1颗</strong></div><div><strong>14颗/盒</strong></div><div><strong>约70天</strong></div></div></div><div className="hero-close"><p className="hero-slogan">Better Man，有心又有力，随时都 Ready.</p><a className="button button-secondary" href="#how-to-use">看看 Better Man 怎么吃 <ArrowDown size={17}/></a></div></div><div className="hero-bottom container"><span>从平时开始，照顾男人的状态。</span><a href="#state" aria-label="继续了解男性状态">向下探索 <ArrowDown size={15}/></a></div></section>; }
const problems = [ { icon: HeartPulse, title: "硬度没有以前好", desc: "以前状态比较容易来，现在有时候来得慢，也没有以前那么容易维持。" }, { icon: Clock3, title: "时间越来越短", desc: "刚进入状态没多久就结束，想控制却越来越难。" }, { icon: TrendingUp, title: "做到一半容易没状态", desc: "开始还可以，但是耐力和状态跟不上，中途容易软下来。" }, { icon: BatteryFull, title: "精神、体力明显下降", desc: "工作一天已经很累，到了晚上更容易觉得没精神、没体力。" }, { icon: Moon, title: "晚上一直起床", desc: "夜里频繁起来，休息不好，第二天精神和体力也容易受到影响。" }, { icon: HeartPulse, title: "夫妻之间开始有压力", desc: "表现没有以前稳定，自己感觉得到，另一半其实也可能感觉得到。" } ];
function Problems() { return <section id="state" className="section section-cream"><div className="container"><div className="lifestyle-feature-head"><SectionHeading eyebrow="01 / UNDERSTAND YOUR STATE" title={<>男人过了一个阶段，<br/>身体的变化骗不了人。</>} desc="有些问题嘴上不说，自己其实最清楚。"/><div className="lifestyle-real-image"><Image src="/images/lifestyle/understand-your-state.png" alt="夜晚坐在床边疲惫思考的成年男性" width={1536} height={1024} loading="lazy" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 900px) calc(100vw - 52px), 55vw"/></div></div><div className="problem-grid">{problems.map((item, i) => <article className="problem-card" key={item.title}><div className="card-top"><item.icon size={23} strokeWidth={1.6}/><span>0{i+1}</span></div><h3>{item.title}</h3><p>{item.desc}</p></article>)}</div><p className="problem-statement">如果你中了不止一个，就别再一直当成“最近比较累”。</p></div></section>; }
function EmotionalTransition() { return <section className="emotional-transition"><div className="container"><p>男人真正怕的，不是年龄变大。<br/>而是——<strong>有心，身体却越来越跟不上。</strong></p><div><span>BETTER MAN</span><strong>Better Man，有心又有力，随时都 Ready。</strong></div></div></section>; }
const benefits = [ [HeartPulse, "硬度状态", "在意的状态，值得从平时开始关注。"], [TrendingUp, "耐力", "照顾男人想要维持的日常状态。"], [Brain, "精神", "忙碌生活里，也别忽略自己的精神。"], [BatteryFull, "体力", "工作与生活，都需要体力跟得上。"], [Zap, "男性活力", "把男人的活力放进日常保养里。"], [Sparkles, "自信", "状态稳一些，面对生活更从容。"] ] as const;
function Benefits({ productAvailable }: { productAvailable: boolean }) { return <section id="benefits" className="section section-cream"><div className={`container benefit-layout ${productAvailable ? "benefit-layout-product" : ""}`}><div className={`benefit-feature ${productAvailable ? "benefit-feature-product" : ""}`}>{!productAvailable && <span>BETTER MAN / PRODUCT FOCUS</span>}{productAvailable ? <Image src="/images/better-man-product.png" alt="Better Man 宝马糖产品盒、独立包装与产品颗粒" width={1254} height={1254} loading="eager" sizes="(max-width: 900px) calc(100vw - 48px), 40vw"/> : <div className="benefit-product-placeholder"><span>产品视觉待上传</span><small>BETTER MAN</small></div>}<p>真正稳定的状态，平时就应该开始照顾。</p></div><div><SectionHeading eyebrow="02 / DAILY WELLNESS" title={<>Better Man，<br/>不只是关键时刻才想到的产品。</>} desc="Better Man 定位于男性日常状态管理，从精力、体力、耐力与男性活力几个方向进行日常补充。不是临时抱佛脚，而是把男人平时的状态慢慢照顾起来。"/><div className="benefit-grid">{benefits.map(([Icon,label,desc]) => <div className="benefit-item" key={label}><span><Icon size={22} strokeWidth={1.7}/></span><div><h3>{label}</h3><p>{desc}</p></div></div>)}</div></div></div></section>; }

const suitableMen = [
  ["工作压力大的男人", "每天工作忙、容易疲累，下班以后整个人已经没什么状态。"],
  ["感觉体力不如以前", "以前熬夜、工作、运动都没什么问题，现在明显感觉恢复比较慢。"],
  ["开始在意男性状态", "硬度、耐力或整体表现没有以前稳定，希望从日常状态开始照顾。"],
  ["经常精神不足", "睡够了还是容易累，白天精神和专注状态不理想。"],
  ["35岁以上开始关注保养的男性", "不一定要等到状态明显下降以后，才开始关注身体和日常状态。"],
  ["想做长期日常管理的人", "不想每次到了关键时刻才处理，而是希望平时就维持自己的整体状态。"],
] as const;
function SuitableMen() { return <section className="section suitable-section"><div className="container"><div className="lifestyle-feature-head"><SectionHeading eyebrow="03 / WHO IT IS FOR" title={<>哪些男性，<br/>适合 Better Man？</>} desc="当生活节奏、年龄和压力开始影响日常状态，就值得认真关注。"/><div className="lifestyle-real-image"><Image src="/images/lifestyle/daily-support.png" alt="在办公环境展示 Better Man 产品的成熟男性" width={1536} height={1024} loading="lazy" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 900px) calc(100vw - 52px), 55vw"/></div></div><div className="suitable-grid">{suitableMen.map(([title, description], index) => <article className="suitable-card" key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>; }

const stateFactors = [
  ["年龄变化", "随着年龄增长，体力和恢复状态可能发生变化。"],
  ["长期压力", "工作、家庭和生活压力长期累积，也可能影响精神和整体生活状态。"],
  ["睡眠不足", "长期熬夜或休息不足，容易影响第二天的精神和体力。"],
  ["生活习惯", "久坐、缺乏运动、饮食不规律等生活方式，也会影响整体健康状态。"],
] as const;
function StateFactors() { return <section className="section state-factors-section"><div className="container state-factors-layout"><div><SectionHeading eyebrow="04 / WHY IT CHANGES" title={<>为什么以前可以，<br/>现在越来越吃力？</>} desc="男人的整体状态，往往会被每天的生活慢慢影响。"/><p className="state-factors-close">所以 Better Man 的定位，不只是关注某一个时刻，而是从男性日常状态开始管理。</p></div><div className="state-factor-list">{stateFactors.map(([title, description], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section>; }

const ingredientItems = [
  { number: "01", label: "CORE INGREDIENT", name: "红东革阿里", english: "TONGKAT ALI", image: "/images/ingredients/tongkat-ali.webp", highlight: "男性活力 · 日常精力 · 体力支持", description: "Better Man 的核心男性草本成分之一，用于支持男性日常活力、精力与体力状态。", tags: ["男性活力", "日常精力", "体力支持"], core: true },
  { number: "02", label: "CORE INGREDIENT", name: "黑玛卡", english: "BLACK MACA", image: "/images/ingredients/black-maca.webp", highlight: "精力 · 耐力 · 男性状态", description: "另一项核心男性草本成分，围绕日常精力、耐力与男性状态进行补充。", tags: ["日常精力", "耐力", "男性状态"], core: true },
  { number: "03", label: "SUPPORTING INGREDIENT", name: "锌", english: "ZINC", image: "/images/ingredients/zinc.webp", highlight: "人体必需微量元素 · 基础营养支持", description: "人体必需的微量元素，为 Better Man 配方补充男性日常所需的基础营养支持。", tags: ["必需微量元素", "基础营养", "日常支持"], core: false },
  { number: "04", label: "SUPPORTING INGREDIENT", name: "罗汉果", english: "MONK FRUIT", image: "/images/ingredients/monk-fruit.webp", highlight: "植物来源 · 配方体验", description: "植物来源的配方组成，主要用于完善整体配方与日常食用体验。", tags: ["植物来源", "配方组成", "食用体验"], core: false },
];
function Ingredients() { return <section id="ingredients" className="section ingredient-showcase"><div className="container"><SectionHeading eyebrow="05 / THE INGREDIENTS" title={<>4大配方成分，<br/>男人的状态从里面开始。</>} desc="以红东革阿里与黑玛卡作为核心，搭配锌与罗汉果，组成 Better Man 的男性日常保养配方。"/><div className="ingredient-stories">{ingredientItems.map((item, index) => <article key={item.number} className={`ingredient-story ${index % 2 ? "ingredient-story-reverse" : ""} ${item.core ? "ingredient-story-core" : ""}`}><div className="ingredient-story-image"><Image src={item.image} alt={`${item.name}原料视觉图片`} width={1536} height={1024} loading="lazy" sizes="(max-width: 650px) 100vw, 50vw"/></div><div className="ingredient-story-copy"><span className="ingredient-story-label">{item.label} / {item.number}</span><span className="ingredient-story-english">{item.english}</span><h3>{item.name}</h3><p className="ingredient-story-highlight">{item.highlight}</p><p className="ingredient-story-description">{item.description}</p><div className="ingredient-tags" aria-label={`${item.name}功效重点`}>{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div><div className="formula-summary"><div><span>BETTER MAN FORMULA</span><h3>两大男性草本 <b>×</b> 两大辅助配方</h3><p>红东革阿里 × 黑玛卡作为核心，从男性活力、精力、性欲与耐力出发；搭配锌与罗汉果，补充男性所需营养并完善整体配方。</p></div><div className="formula-summary-slogan"><span>Better Man</span><strong>有心又有力，随时都 Ready。</strong></div></div></div></section>; }
const usePoints = [
  { number: "01", title: "5天1颗", lead: "简单好记，不需要每天补充。", description: "每5天食用1颗，按照规律持续补充即可。" },
  { number: "02", title: "一盒14颗", lead: "一盒约可食用70天。", description: "按照每5天1颗的建议食用方式，一盒14颗约可食用70天。" },
  { number: "03", title: "坚持规律", lead: "把男人的状态放在平时照顾。", description: "Better Man 更强调平时规律补充，从精神、体力、男性活力与整体状态出发，让保养成为日常，而不是等到需要的时候才开始。" },
];
function HowToUse() { return <section id="how-to-use" className="section how-to-use-section"><div className="container"><div className="how-to-use-heading"><div className="how-to-kicker"><span>08 / HOW TO USE</span><strong>简单吃，坚持养</strong></div><h2>不需要天天吃，<br/><em>5天1颗就够。</em></h2><p>简单的食用方式，更容易长期坚持。<br/>Better Man 不是临时需要时才想起，而是把男人的状态放在平时慢慢照顾。</p></div><div className="how-to-mobile-photo"><Image src="/images/how-to-use/better-man-handheld.png" alt="真人手持 Better Man 独立包装" width={1254} height={1254} loading="lazy" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 1200px) 42vw, 500px"/></div><div className="how-to-main"><div className="dose-visual" aria-label="每5天食用1颗"><span className="dose-caption">THE BETTER MAN ROUTINE</span><div className="dose-step"><strong>5</strong><div><b>DAYS</b><span>每5天</span></div></div><div className="dose-arrow" aria-hidden="true"><span></span><ArrowDown size={24}/></div><div className="dose-step dose-step-one"><strong>1</strong><div><b>PIECE</b><span>1颗</span></div></div><p>每5天 <i>·</i> 1颗</p></div><div className="use-points">{usePoints.map((item) => <article key={item.number}><span>{item.number}</span><div><h3>{item.title}</h3><strong>{item.lead}</strong><p>{item.description}</p></div></article>)}</div></div><div className="how-to-close"><span>BETTER MAN / DAILY ROUTINE</span><h3>不是等到要用的时候，<br/>才想起自己的状态。</h3><p>男人的状态，本来就应该平时养好。</p><div className="how-to-slogan"><b>BETTER MAN</b><strong>有心又有力，随时都 <em>Ready。</em></strong></div></div></div></section>; }
const ages = [ { range: "30—40", items: "工作压力 · 精神不足 · 体力消耗快 · 耐力开始出现变化", focus: "精神 / 体力 / 耐力" }, { range: "40—50", items: "硬度状态 · 耐力 · 体力 · 男性活力更值得关注", focus: "状态 / 活力 / 耐力" }, { range: "50—60+", items: "精神体力 · 夜间休息 · 男性活力 · 整体状态长期保养", focus: "日常保养 / 精神 / 活力" } ];
function AgeGroups() { return <section className="section section-cream"><div className="container"><div className="lifestyle-feature-head lifestyle-feature-head-age"><SectionHeading eyebrow="06 / EVERY STAGE" title={<>年纪不同，<br/>男人面对的问题也不同。</>}/><div className="lifestyle-real-image"><Image src="/images/lifestyle/every-stage.png" alt="在户外运动、展现精神体力与活力的成熟男性" width={1536} height={1024} loading="lazy" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 900px) calc(100vw - 52px), 55vw"/></div></div><div className="age-grid">{ages.map((age) => <article className="age-card" key={age.range}><span>YEARS</span><h3>{age.range}<small>岁</small></h3><p>{age.items}</p><div><small>关注重点</small><strong>{age.focus}</strong></div></article>)}</div></div></section>; }
function Disclaimer() { return <p className="review-disclaimer">以上内容为顾客个人使用体验分享，实际感受会因个人身体状态及生活习惯而有所不同。</p>; }
function CustomerReviews({ photos, videos }: { photos: PhotoReview[]; videos: VideoReview[] }) {
  const [photoIndex, setPhotoIndex] = useState<number | null>(null);
  const [activeVideo, setActiveVideo] = useState<VideoReview | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const available = photos.flatMap((p, i) => p.available ? [i] : []);
  const step = (direction: number) => setPhotoIndex((current) => current === null || !available.length ? null : available[(available.indexOf(current) + direction + available.length) % available.length]);
  useEffect(() => {
    if (photoIndex === null && !activeVideo) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") { setPhotoIndex(null); setActiveVideo(null); } if (photoIndex !== null && e.key === "ArrowLeft") step(-1); if (photoIndex !== null && e.key === "ArrowRight") step(1); };
    document.body.style.overflow = "hidden";
    window.addEventListener("keydown", onKey);
    return () => { videoRef.current?.pause(); document.body.style.overflow = ""; window.removeEventListener("keydown", onKey); };
  });
  const order: ({ kind: "photo"; item: PhotoReview } | { kind: "video"; item: VideoReview })[] = [
    { kind: "video", item: videos[0] }, { kind: "photo", item: photos[0] },
    { kind: "photo", item: photos[1] }, { kind: "video", item: videos[1] },
    { kind: "photo", item: photos[2] }, { kind: "photo", item: photos[3] },
  ];
  const photo = photoIndex !== null ? photos[photoIndex] : null;
  return <section id="reviews" className="section customer-reviews"><div className="container">
    <div className="reviews-heading"><div><span>09 / REAL CUSTOMER FEEDBACK</span><strong>真实顾客反馈</strong></div><div><h2>不是我们说好，<br/><em>是他们用了以后这样说。</em></h2><p>从男性状态、精神体力到日常体验，<br/>看看 Better Man 顾客使用后的真实反馈。</p></div></div>
    <div className="reviews-trust"><div><span>REAL PEOPLE</span><i></i><span>REAL FEEDBACK</span><i></i><span>REAL EXPERIENCE</span></div><p>真实顾客 · 真实反馈 · 真实体验</p></div>
    <div className="mixed-grid"><div className="mobile-review-subhead mobile-video-subhead"><span>CUSTOMER STORIES</span><h3>听他们自己怎么说。</h3></div><div className="mobile-review-subhead mobile-photo-subhead"><span>REAL FEEDBACK</span><h3>来自顾客的真实反馈。</h3></div>{order.map((entry, i) => entry.kind === "photo" ? <button key={`p${entry.item.id}`} type="button" className={`mixed-card mixed-photo mixed-${i}`} disabled={!entry.item.available} onClick={() => setPhotoIndex(photos.indexOf(entry.item))} aria-label={entry.item.available ? `查看${entry.item.name}完整图片` : `${entry.item.name}素材待上传`}>
      {entry.item.available ? <Image src={entry.item.image} alt={entry.item.name} width={784} height={1280} loading="lazy" sizes="(max-width: 650px) calc(100vw - 36px), (max-width: 900px) 50vw, 25vw"/> : <span className="mixed-placeholder"><b>IMAGE / 0{entry.item.id}</b><small>真实图片待上传</small></span>}<span className="mixed-label"><span>REAL FEEDBACK / 0{entry.item.id}</span><ArrowUpRight size={16}/></span>
    </button> : <button key={`v${entry.item.id}`} type="button" className={`mixed-card mixed-video mixed-${i}`} disabled={!entry.item.available} onClick={() => setActiveVideo(entry.item)} aria-label={entry.item.available ? `播放${entry.item.title}` : `${entry.item.title}素材待上传`}>
      {entry.item.available ? <video src={entry.item.video} poster={entry.item.posterAvailable ? entry.item.poster : undefined} muted playsInline preload="metadata" aria-hidden="true"/> : <span className="mixed-video-placeholder"><b>VIDEO / 0{entry.item.id}</b><strong>顾客视频分享</strong><small>竖版视频待上传</small></span>}{entry.item.available && <span className="play-circle"><Play fill="currentColor" size={21}/></span>}<span className="mixed-label"><span>REAL VIDEO / 0{entry.item.id}</span><Play size={16}/></span>
    </button>)}</div>
    <Disclaimer/>
    <div className="review-conversion"><div><span>WHY THEY STARTED</span><h3>很多人一开始，<br/><em>也只是想先试试看。</em></h3></div><div><p>真正让他们继续选择 Better Man 的，是自己慢慢感受到状态的变化。</p><strong>你不需要一次改变全部。<br/>先给自己一次机会。</strong><div className="review-conversion-action"><WaButton>我也想试试看</WaButton><small>WhatsApp 一对一咨询</small></div></div></div>
  </div>
  {photo?.available && <div className="modal-backdrop" role="presentation" onMouseDown={() => setPhotoIndex(null)}><div className="lightbox" role="dialog" aria-modal="true" aria-label={photo.name} onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setPhotoIndex(null)} aria-label="关闭图片"><X/></button><button className="modal-arrow left" onClick={() => step(-1)} aria-label="上一张"><ArrowLeft/></button><Image src={photo.image} alt={photo.name} width={1000} height={1100} className="lightbox-image"/><button className="modal-arrow right" onClick={() => step(1)} aria-label="下一张"><ArrowRight/></button><span className="modal-count">{available.indexOf(photoIndex!)+1} / {available.length}</span></div></div>}
  {activeVideo && <div className="modal-backdrop" role="presentation" onMouseDown={() => setActiveVideo(null)}><div className="video-modal" role="dialog" aria-modal="true" aria-label={activeVideo.title} onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setActiveVideo(null)} aria-label="关闭视频"><X/></button><video ref={videoRef} src={activeVideo.video} poster={activeVideo.posterAvailable ? activeVideo.poster : undefined} controls playsInline preload="metadata" autoPlay/></div></div>}
  </section>;
}

function Trust() { return <section id="why-better-man" className="section why-better"><div className="container"><div className="why-heading"><div><span>07 / WHY BETTER MAN</span><strong>为什么选择 Better Man</strong></div><div><h2>男人要的，<br/><em>不只是那一下。</em><br/><b>是整个人的状态回来。</b></h2><p>真正影响男人表现的，从来不只是某一个瞬间。<br/>精神、体力、耐力、男性活力和整体状态，每一个都重要。</p><strong>Better Man，从男人真正关心的状态出发。</strong></div></div><div className="why-mobile-value"><div className="why-mobile-cards"><article><span className="why-mobile-number">01</span><small>MEN&apos;S FORMULA</small><h3>男性针对性配方</h3><p>以红东革阿里与黑玛卡为核心，围绕男性日常精力、体力、耐力与活力需求。</p></article><article><span className="why-mobile-number">02</span><small>WHOLE STATE</small><h3>不只是关注一个方面</h3><p>从精神、体力、耐力到男性活力，关注男人整体状态。</p></article><article><span className="why-mobile-number">03</span><small>DAILY SUPPORT</small><h3>从平时开始照顾</h3><p>不是只在某一个时刻才想起来，而是把男性状态放进日常管理。</p></article></div><div className="why-mobile-cta"><h3>不用一次买很多，<br/>先从一盒开始。</h3><p>想先了解适不适合自己，可以直接 WhatsApp 一对一咨询。</p><WaButton>WhatsApp 咨询 Better Man</WaButton></div></div></div></section>; }
const faqs = [
  { question: "Better Man 怎么吃？", paragraphs: ["建议每5天食用1颗，按照规律持续补充即可。", "不需要天天吃，也不需要等到有需要的时候才想起食用。"] },
  { question: "一盒有多少颗？可以吃多久？", paragraphs: ["每盒共有14颗。", "按照每5天1颗的建议食用方式，一盒约可食用70天。"] },
  { question: "Better Man 主要有什么成分？", paragraphs: ["Better Man 结合4种配方成分，以红东革阿里与黑玛卡作为核心，搭配锌与罗汉果，从男性日常精神、体力、耐力与活力等方向进行补充。"] },
  { question: "Better Man 主要适合哪些男性？", paragraphs: ["适合开始感觉精神、体力、耐力或男性状态不如以前，希望通过日常调理维持整体状态的成年男性。"] },
  { question: "一般多久会感觉到变化？", paragraphs: ["每个人的身体状态、生活习惯和吸收情况不同，因此实际感受时间也会有所不同。", "Better Man 更强调规律补充与持续调理，而不是把它当成只追求一次即时感觉的产品。"] },
  { question: "Better Man 是有需要的时候才吃吗？", paragraphs: ["不是。", "Better Man 的理念是把男性状态放在平时照顾，而不是等到真正需要的时候才开始。", "按照建议每5天1颗规律补充，让日常保养变得更简单。"] },
  { question: "第一次吃，建议先买几盒？", paragraphs: ["如果是第一次接触 Better Man，可以先根据自己的需求选择适合的配套。", "如果不确定应该怎么选择，可以直接通过 WhatsApp 联系我们，我们会根据你的情况提供产品与食用方式说明。"] },
  { question: "食用 Better Man 需要注意什么？", paragraphs: ["请按照建议食用方式使用，不需要自行增加食用量。", "如果正在服用药物、正在接受治疗，或本身有特殊健康状况，建议食用前先咨询医生或合格医疗专业人士。"] },
  { question: "Better Man 多少钱？", paragraphs: ["Better Man 不同地区及活动期间的配套可能有所不同。", "点击 WhatsApp 联系我们，即可查看目前最新配套与优惠。"], link: "查看目前优惠 →" },
  { question: "怎样下单？", paragraphs: ["点击网站任何一个绿色 WhatsApp 按钮，即可进入一对一咨询与下单。", "告诉我们你所在的地区，我们会提供目前可选择的配套、价格及下单方式。"], link: "WhatsApp 立即咨询 ↗", button: true },
];
function LateConversion() { return <section className="section late-conversion"><div className="container late-conversion-inner"><div><Eyebrow>START FROM TODAY</Eyebrow><h2>不需要等到“真的不行了”，<br/>才开始照顾。</h2></div><div><p>很多男人年轻的时候不会特别注意自己的状态。工作越来越忙、睡眠越来越少、压力越来越大以后，才发现精神、体力、耐力和整体表现已经不像以前。</p><strong>如果你已经开始感觉到变化，就是可以开始关注自己的时候。</strong><WaButton>WhatsApp 私下了解 Better Man</WaButton></div></div></section>; }
function FAQ() { return <section id="faq" className="section section-cream"><div className="container faq-layout"><div><SectionHeading eyebrow="10 / FAQ" title="你可能还想了解" desc="有关 Better Man 的常见问题，都在这里。"/><WaButton>还有疑问？WhatsApp 咨询</WaButton></div><div className="faq-list">{faqs.map((item,i) => <details key={item.question}><summary><span className="faq-number">{String(i+1).padStart(2,"0")}</span><strong>{item.question}</strong><ChevronDown size={20}/></summary><div className="faq-answer"><div>{item.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{item.link && <a className={item.button ? "faq-answer-button" : "faq-answer-link"} href={whatsappHref()} target="_blank" rel="noopener noreferrer">{item.link}</a>}</div></div></details>)}</div></div></section>; }
function FinalCTA() { return <section className="final-cta"><div className="container final-inner"><Eyebrow>BETTER MAN</Eyebrow><h2>有些状态，<br/><em>拖着不会自己变回以前。</em></h2><p>如果你已经发现精神、体力、耐力，甚至男人状态开始不如以前，与其继续拖，不如从现在开始认真照顾自己的状态。</p><div className="final-slogan">Better Man，有心又有力，随时都 Ready。</div><WaButton light>WhatsApp 私下了解</WaButton><small>了解产品、吃法及目前配套。</small></div></section>; }
function Footer() { return <footer className="footer"><div className="container"><div className="footer-main"><div><a className="brand footer-brand" href="#home" aria-label="Better Man 首页"><BrandLogo/></a></div><nav aria-label="页脚导航"><a href="#benefits">产品介绍</a><a href="#ingredients">4大成分</a><a href="#how-to-use">食用方式</a><a href="#reviews">顾客反馈</a><a href="#faq">FAQ</a><a href="/privacy/">Privacy Policy</a><a href="/terms/">Terms</a></nav></div><div className="footer-bottom"><p>本网站提供的资料仅供一般产品资讯与日常保健参考，并非医疗建议、诊断或治疗用途。如有健康相关疑问，请咨询专业医疗人员。</p><span>© {new Date().getFullYear()} Better Man. All rights reserved.</span></div></div></footer>; }
function FloatingWhatsApp() { return <a className="floating-wa" href={whatsappHref()} target="_blank" rel="noopener noreferrer" aria-label="通过 WhatsApp 咨询 Better Man"><MessageCircle size={23} fill="currentColor"/><span>WhatsApp 咨询</span></a>; }
export function Site({ productAvailable, photos, videos }: { productAvailable: boolean; photos: PhotoReview[]; videos: VideoReview[] }) { return <><Header/><main><Hero/><Problems/><Benefits productAvailable={productAvailable}/><SuitableMen/><StateFactors/><Ingredients/><AgeGroups/><Trust/><HowToUse/><CustomerReviews photos={photos} videos={videos}/><FAQ/><FinalCTA/></main><Footer/><FloatingWhatsApp/></>; }






