"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, BatteryFull, Brain, ChevronDown, Clock3, HeartPulse, Menu, MessageCircle, Moon, Play, Sparkles, TrendingUp, X, Zap } from "lucide-react";
import type { PhotoReview, VideoReview } from "@/data/reviews";
import { whatsappHref } from "@/config/site";

const nav = [ ["产品介绍", "#benefits"], ["核心成分", "#ingredients"], ["食用方式", "#how-to-use"], ["顾客反馈", "#reviews"], ["FAQ", "#faq"] ];
function BrandLogo() { return <span className="brand-logo"><Image src="/brand/better-man-logo.png" alt="Better Man 官方 Logo" width={1391} height={970} priority /></span>; }
function WaButton({ children = "WhatsApp 咨询", light = false, className = "" }: { children?: React.ReactNode; light?: boolean; className?: string }) { return <a className={`button button-whatsapp ${light ? "button-whatsapp-light" : ""} ${className}`} href={whatsappHref()} target="_blank" rel="noopener noreferrer" aria-label="通过 WhatsApp 咨询 Better Man"><MessageCircle size={18}/>{children}<ArrowUpRight size={17}/></a>; }
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
function SectionHeading({ eyebrow, title, desc, center = false }: { eyebrow: string; title: React.ReactNode; desc?: React.ReactNode; center?: boolean }) { return <div className={`section-heading ${center ? "center" : ""}`}><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{desc && <p className="section-desc">{desc}</p>}</div>; }
function Header() { const [open, setOpen] = useState(false); return <header className="site-header"><div className="container header-inner"><a className="brand" href="#home" aria-label="Better Man 首页"><BrandLogo/></a><nav className="desktop-nav" aria-label="主导航">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><WaButton className="header-cta">WhatsApp 咨询</WaButton><button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-nav" aria-label={open ? "关闭菜单" : "打开菜单"}>{open ? <X/> : <Menu/>}</button></div>{open && <nav id="mobile-nav" className="mobile-nav" aria-label="移动导航"><a className="mobile-brand" href="#home" onClick={() => setOpen(false)}><BrandLogo/></a>{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}<ArrowUpRight size={16}/></a>)}<WaButton>WhatsApp 立即咨询</WaButton></nav>}</header>; }
function Hero() { return <section id="home" className="hero"><div className="container hero-grid"><div className="hero-copy"><Eyebrow>BETTER MAN / 男性日常状态保养</Eyebrow><h1>不够硬、撑不久、<br/><em>状态越来越难维持？</em></h1><p className="hero-second">男人有没有力，<br/>自己最清楚。</p><p className="hero-desc">年龄、压力、休息和生活状态改变，精神、体力、耐力，甚至关键时刻的表现，都可能慢慢不像以前。</p><div className="hero-intro"><strong>BETTER MAN 宝马糖</strong><span>从平时开始照顾男人的状态。</span></div><p className="hero-slogan">Better Man，有心又有力，随时都 Ready。</p><div className="hero-metrics"><div><strong>05</strong><span>每5天1颗</span></div><div><strong>14</strong><span>每盒14颗</span></div><div><strong>70<span className="metric-unit">天</span></strong><span>约70天使用周期</span></div></div><div className="hero-actions"><WaButton>WhatsApp 私下了解</WaButton><a className="button button-secondary" href="#how-to-use">看看 Better Man 怎么吃 <ArrowDown size={17}/></a></div></div><div className="hero-art"><div className="hero-product"><Image src="/images/hero/better-man-product.png" alt="Better Man 宝马糖产品盒与独立包装" width={1254} height={1254} priority className="product-image" sizes="(max-width: 650px) calc(100vw - 36px), (max-width: 900px) min(620px, calc(100vw - 48px)), 45vw"/></div></div></div><div className="hero-bottom container"><span>从平时开始，照顾男人的状态。</span><a href="#state" aria-label="继续了解男性状态">向下探索 <ArrowDown size={15}/></a></div></section>; }
const problems = [ { icon: HeartPulse, title: "硬度没有以前好", desc: "以前状态比较容易来，现在有时候来得慢，也没有以前那么容易维持。" }, { icon: Clock3, title: "时间越来越短", desc: "刚进入状态没多久就结束，想控制却越来越难。" }, { icon: TrendingUp, title: "做到一半容易没状态", desc: "开始还可以，但是耐力和状态跟不上，中途容易软下来。" }, { icon: BatteryFull, title: "精神、体力明显下降", desc: "工作一天已经很累，到了晚上更容易觉得没精神、没体力。" }, { icon: Moon, title: "晚上一直起床", desc: "夜里频繁起来，休息不好，第二天精神和体力也容易受到影响。" }, { icon: HeartPulse, title: "夫妻之间开始有压力", desc: "表现没有以前稳定，自己感觉得到，另一半其实也可能感觉得到。" } ];
function Problems() { return <section id="state" className="section section-cream"><div className="container"><SectionHeading eyebrow="01 / UNDERSTAND YOUR STATE" title={<>男人过了一个阶段，<br/>身体的变化骗不了人。</>} desc="有些问题嘴上不说，自己其实最清楚。"/><div className="problem-grid">{problems.map((item, i) => <article className="problem-card" key={item.title}><div className="card-top"><item.icon size={23} strokeWidth={1.6}/><span>0{i+1}</span></div><h3>{item.title}</h3><p>{item.desc}</p></article>)}</div><p className="problem-statement">如果你中了不止一个，就别再一直当成“最近比较累”。</p></div></section>; }
function EmotionalTransition() { return <section className="emotional-transition"><div className="container"><p>男人真正怕的，不是年龄变大。<br/>而是——<strong>有心，身体却越来越跟不上。</strong></p><div><span>BETTER MAN</span><strong>Better Man，有心又有力，随时都 Ready。</strong></div></div></section>; }
const benefits = [ [HeartPulse, "硬度状态", "在意的状态，值得从平时开始关注。"], [TrendingUp, "耐力", "照顾男人想要维持的日常状态。"], [Brain, "精神", "忙碌生活里，也别忽略自己的精神。"], [BatteryFull, "体力", "工作与生活，都需要体力跟得上。"], [Zap, "男性活力", "把男人的活力放进日常保养里。"], [Sparkles, "自信", "状态稳一些，面对生活更从容。"] ] as const;
function Benefits({ productAvailable }: { productAvailable: boolean }) { return <section id="benefits" className="section section-cream"><div className={`container benefit-layout ${productAvailable ? "benefit-layout-product" : ""}`}><div className={`benefit-feature ${productAvailable ? "benefit-feature-product" : ""}`}>{!productAvailable && <span>BETTER MAN / PRODUCT FOCUS</span>}{productAvailable ? <Image src="/images/better-man-product.png" alt="Better Man 宝马糖产品盒、独立包装与产品颗粒" width={1254} height={1254} loading="eager" sizes="(max-width: 900px) calc(100vw - 48px), 40vw"/> : <div className="benefit-product-placeholder"><span>产品视觉待上传</span><small>BETTER MAN</small></div>}<p>真正稳定的状态，平时就应该开始照顾。</p></div><div><SectionHeading eyebrow="02 / DAILY WELLNESS" title={<>Better Man，<br/>不只是为了关键时刻。</>} desc="真正稳定的状态，平时就应该开始照顾。"/><div className="benefit-grid">{benefits.map(([Icon,label,desc]) => <div className="benefit-item" key={label}><span><Icon size={22} strokeWidth={1.7}/></span><div><h3>{label}</h3><p>{desc}</p></div></div>)}</div></div></div></section>; }
const ingredientItems = [
  { number: "01", label: "CORE INGREDIENT", name: "红东革阿里", english: "TONGKAT ALI", image: "/images/ingredients/tongkat-ali.webp", highlight: "男性活力 · 睾酮支持 · 体力 · 耐力", description: "Better Man 的核心男性草本成分。红东革阿里主要用于支持男性活力与健康睾酮水平，同时帮助维持体力、精力与耐力表现。特别适合随着年龄增长，感觉精神、体力和整体男性状态不如以前的成年男性。", tags: ["男性活力", "睾酮支持", "体力耐力"], core: true },
  { number: "02", label: "CORE INGREDIENT", name: "黑玛卡", english: "BLACK MACA", image: "/images/ingredients/black-maca.webp", highlight: "精力 · 性欲 · 耐力 · 运动表现", description: "黑玛卡是 Better Man 的另一大核心草本成分，重点围绕男性精力、性欲与耐力表现，同时支持日常体力及运动状态。与红东革阿里搭配，从男性活力与身体状态两个方向进行日常补充。", tags: ["提升精力", "性欲支持", "耐力表现"], core: true },
  { number: "03", label: "SUPPORTING INGREDIENT", name: "锌", english: "ZINC", image: "/images/ingredients/zinc.webp", highlight: "睾酮维持 · 生殖健康 · 免疫功能", description: "锌是人体必需的微量元素，对正常免疫功能、生殖健康以及正常睾酮水平的维持具有重要作用。加入 Better Man 配方，让男性草本之外，也兼顾男性日常所需的基础营养支持。", tags: ["睾酮维持", "生殖健康", "免疫功能"], core: false },
  { number: "04", label: "SUPPORTING INGREDIENT", name: "罗汉果", english: "MONK FRUIT", image: "/images/ingredients/monk-fruit.webp", highlight: "天然甜味 · 植物来源 · 配方体验", description: "罗汉果含有天然甜味成分及植物抗氧化成分，在 Better Man 配方中主要负责改善整体食用体验，并作为植物来源配方的一部分，让日常补充更加容易坚持。", tags: ["天然甜味", "植物来源", "日常食用"], core: false },
];
function Ingredients() { return <section id="ingredients" className="section ingredient-showcase"><div className="container"><SectionHeading eyebrow="04 / THE INGREDIENTS" title={<>4大配方成分，<br/>男人的状态从里面开始。</>} desc="以红东革阿里与黑玛卡作为核心，搭配锌与罗汉果，组成 Better Man 的男性日常保养配方。"/><div className="ingredient-stories">{ingredientItems.map((item, index) => <article key={item.number} className={`ingredient-story ${index % 2 ? "ingredient-story-reverse" : ""} ${item.core ? "ingredient-story-core" : ""}`}><div className="ingredient-story-image"><Image src={item.image} alt={`${item.name}原料视觉图片`} width={1536} height={1024} loading="lazy" sizes="(max-width: 650px) 100vw, 50vw"/></div><div className="ingredient-story-copy"><span className="ingredient-story-label">{item.label} / {item.number}</span><span className="ingredient-story-english">{item.english}</span><h3>{item.name}</h3><p className="ingredient-story-highlight">{item.highlight}</p><p className="ingredient-story-description">{item.description}</p><div className="ingredient-tags" aria-label={`${item.name}功效重点`}>{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div><div className="formula-summary"><div><span>BETTER MAN FORMULA</span><h3>两大男性草本 <b>×</b> 两大辅助配方</h3><p>红东革阿里 × 黑玛卡作为核心，从男性活力、精力、性欲与耐力出发；搭配锌与罗汉果，补充男性所需营养并完善整体配方。</p></div><div className="formula-summary-slogan"><span>Better Man</span><strong>有心又有力，随时都 Ready。</strong></div></div></div></section>; }
function Philosophy() { return <section className="section philosophy"><div className="container philosophy-layout"><div><Eyebrow>04 / THE PHILOSOPHY</Eyebrow><h2>不是等到需要的时候，<br/><em>才想起来。</em></h2><p>Better Man 的概念，不是只顾关键时刻。而是从平时开始，把精神、体力、耐力和男人的状态一起照顾。</p><p className="philosophy-slogan">Better Man，有心又有力，随时都 Ready。</p><WaButton light>了解产品配套</WaButton></div><div className="philosophy-panel"><span className="panel-caption">A SIMPLE ROUTINE</span><div className="panel-big">每 <strong>5</strong> 天 <strong>1</strong> 颗</div><div className="routine"><div><span>DAY 01</span><strong>服用 1 颗</strong></div><ArrowRight size={18}/><div><span>间隔 4 天</span><strong>日常状态保养</strong></div><ArrowRight size={18}/><div><span>DAY 06</span><strong>再服用 1 颗</strong></div></div></div></div></section>; }
const usePoints = [
  { number: "01", title: "5天1颗", lead: "简单好记，不需要每天补充。", description: "每5天食用1颗，按照规律持续补充即可。" },
  { number: "02", title: "一盒14颗", lead: "一盒约可食用70天。", description: "按照每5天1颗的建议食用方式，一盒14颗约可食用70天。" },
  { number: "03", title: "坚持调理", lead: "把男人的状态放在平时照顾。", description: "Better Man 更强调平时规律补充，从精神、体力、男性活力与整体状态出发，让保养成为日常，而不是等到需要的时候才开始。" },
];
function HowToUse() { return <section id="how-to-use" className="section how-to-use-section"><div className="container"><div className="how-to-use-heading"><div className="how-to-kicker"><span>HOW TO USE</span><strong>简单吃，坚持养</strong></div><h2>不需要天天吃，<br/><em>5天1颗就够。</em></h2><p>简单的食用方式，更容易长期坚持。<br/>Better Man 不是临时需要时才想起，而是把男人的状态放在平时慢慢照顾。</p></div><div className="how-to-main"><div className="dose-visual" aria-label="每5天食用1颗"><span className="dose-caption">THE BETTER MAN ROUTINE</span><div className="dose-step"><strong>5</strong><div><b>DAYS</b><span>每5天</span></div></div><div className="dose-arrow" aria-hidden="true"><span></span><ArrowDown size={24}/></div><div className="dose-step dose-step-one"><strong>1</strong><div><b>PIECE</b><span>1颗</span></div></div><p>每5天 <i>·</i> 1颗</p></div><div className="use-points">{usePoints.map((item) => <article key={item.number}><span>{item.number}</span><div><h3>{item.title}</h3><strong>{item.lead}</strong><p>{item.description}</p></div></article>)}</div></div><div className="how-to-close"><span>BETTER MAN / DAILY ROUTINE</span><h3>不是等到要用的时候，<br/>才想起自己的状态。</h3><p>男人的状态，本来就应该平时养好。</p><div className="how-to-slogan"><b>BETTER MAN</b><strong>有心又有力，随时都 <em>Ready。</em></strong></div></div></div></section>; }
const ages = [ { range: "30—40", items: "工作压力 · 精神不足 · 体力消耗快 · 耐力开始出现变化", focus: "精神 / 体力 / 耐力" }, { range: "40—50", items: "硬度状态 · 耐力 · 体力 · 男性活力更值得关注", focus: "状态 / 活力 / 耐力" }, { range: "50—60+", items: "精神体力 · 夜间休息 · 男性活力 · 整体状态长期保养", focus: "日常保养 / 精神 / 活力" } ];
function AgeGroups() { return <section className="section section-cream"><div className="container"><SectionHeading eyebrow="06 / EVERY STAGE" title={<>年纪不同，<br/>男人面对的问题也不同。</>}/><div className="age-grid">{ages.map((age) => <article className="age-card" key={age.range}><span>YEARS</span><h3>{age.range}<small>岁</small></h3><p>{age.items}</p><div><small>关注重点</small><strong>{age.focus}</strong></div></article>)}</div></div></section>; }
function Disclaimer() { return <p className="review-disclaimer">以上内容为顾客个人使用体验分享，实际感受会因个人身体状态及生活习惯而有所不同。</p>; }
function CustomerReviews({ photos, videos }: { photos: PhotoReview[]; videos: VideoReview[] }) {
  const [photoIndex, setPhotoIndex] = useState<number | null>(null);
  const [activeVideo, setActiveVideo] = useState<VideoReview | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const available = photos.flatMap((p, i) => p.available ? [i] : []);
  const step = (direction: number) => setPhotoIndex((current) => current === null || !available.length ? null : available[(available.indexOf(current) + direction + available.length) % available.length]);
  useEffect(() => {
    if (photoIndex === null && !activeVideo) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") { setPhotoIndex(null); setActiveVideo(null); } if (photoIndex !== null && e.key === "ArrowLeft") step(-1); if (photoIndex !== null && e.key === "ArrowRight") step(1); };
    document.body.style.overflow = "hidden";
    window.addEventListener("keydown", onKey);
    return () => { videoRef.current?.pause(); document.body.style.overflow = ""; window.removeEventListener("keydown", onKey); };
  });
  const order: ({ kind: "photo"; item: PhotoReview } | { kind: "video"; item: VideoReview })[] = [
    { kind: "video", item: videos[0] }, { kind: "photo", item: photos[0] },
    { kind: "photo", item: photos[1] }, { kind: "video", item: videos[1] },
    { kind: "photo", item: photos[2] }, { kind: "photo", item: photos[3] },
  ];
  const photo = photoIndex !== null ? photos[photoIndex] : null;
  return <section id="reviews" className="section customer-reviews"><div className="container">
    <div className="reviews-heading"><div><span>REAL CUSTOMER FEEDBACK</span><strong>真实顾客反馈</strong></div><div><h2>不是我们说好，<br/><em>是他们用了以后这样说。</em></h2><p>从男性状态、精神体力到日常体验，<br/>看看 Better Man 顾客使用后的真实反馈。</p></div></div>
    <div className="reviews-trust"><div><span>REAL PEOPLE</span><i></i><span>REAL FEEDBACK</span><i></i><span>REAL EXPERIENCE</span></div><p>真实顾客 · 真实反馈 · 真实体验</p></div>
    <div className="mixed-grid">{order.map((entry, i) => entry.kind === "photo" ? <button key={`p${entry.item.id}`} type="button" className={`mixed-card mixed-photo mixed-${i}`} disabled={!entry.item.available} onClick={() => setPhotoIndex(photos.indexOf(entry.item))} aria-label={entry.item.available ? `查看${entry.item.name}完整图片` : `${entry.item.name}素材待上传`}>
      {entry.item.available ? <Image src={entry.item.image} alt={entry.item.name} width={784} height={1280} loading="lazy" sizes="(max-width: 650px) calc(100vw - 36px), (max-width: 900px) 50vw, 25vw"/> : <span className="mixed-placeholder"><b>IMAGE / 0{entry.item.id}</b><small>真实图片待上传</small></span>}<span className="mixed-label"><span>REAL FEEDBACK / 0{entry.item.id}</span><ArrowUpRight size={16}/></span>
    </button> : <button key={`v${entry.item.id}`} type="button" className={`mixed-card mixed-video mixed-${i}`} disabled={!entry.item.available} onClick={() => setActiveVideo(entry.item)} aria-label={entry.item.available ? `播放${entry.item.title}` : `${entry.item.title}素材待上传`}>
      {entry.item.available ? <video src={entry.item.video} poster={entry.item.posterAvailable ? entry.item.poster : undefined} muted playsInline preload="metadata" aria-hidden="true"/> : <span className="mixed-video-placeholder"><b>VIDEO / 0{entry.item.id}</b><strong>顾客视频分享</strong><small>竖版视频待上传</small></span>}{entry.item.available && <span className="play-circle"><Play fill="currentColor" size={21}/></span>}<span className="mixed-label"><span>REAL VIDEO / 0{entry.item.id}</span><Play size={16}/></span>
    </button>)}</div>
    <Disclaimer/>
    <div className="review-conversion"><div><span>WHY THEY STARTED</span><h3>很多人一开始，<br/><em>也只是想先试试看。</em></h3></div><div><p>真正让他们继续选择 Better Man 的，<br/>不是广告说了什么，<br/>而是自己感受到状态的变化。</p><strong>你不需要一次改变全部。<br/>先给自己一次机会。</strong><div className="review-conversion-action"><WaButton>我也想试试看</WaButton><small>WhatsApp 一对一咨询</small></div></div></div>
  </div>
  {photo?.available && <div className="modal-backdrop" role="presentation" onMouseDown={() => setPhotoIndex(null)}><div className="lightbox" role="dialog" aria-modal="true" aria-label={photo.name} onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setPhotoIndex(null)} aria-label="关闭图片"><X/></button><button className="modal-arrow left" onClick={() => step(-1)} aria-label="上一张"><ArrowLeft/></button><Image src={photo.image} alt={photo.name} width={1000} height={1100} className="lightbox-image"/><button className="modal-arrow right" onClick={() => step(1)} aria-label="下一张"><ArrowRight/></button><span className="modal-count">{available.indexOf(photoIndex!)+1} / {available.length}</span></div></div>}
  {activeVideo && <div className="modal-backdrop" role="presentation" onMouseDown={() => setActiveVideo(null)}><div className="video-modal" role="dialog" aria-modal="true" aria-label={activeVideo.title} onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setActiveVideo(null)} aria-label="关闭视频"><X/></button><video ref={videoRef} src={activeVideo.video} poster={activeVideo.posterAvailable ? activeVideo.poster : undefined} controls playsInline preload="metadata" autoPlay/></div></div>}
  </section>;
}
const whyReasons = [
  { number: "01", title: <>状态不是突然变差的，<br/>也不会一夜变回来。</>, highlight: "日常调理 · 长期维持", description: "精神越来越差、体力跟不上、耐力下降，甚至关键时刻开始力不从心，往往都是身体状态长期累积的结果。", emphasis: "Better Man 不是等到要用的时候才想起，而是从平时开始，把男人该有的状态慢慢养回来。" },
  { number: "02", title: <>不用天天吃，<br/>5天1颗就够。</>, highlight: "5 DAYS · 1 PIECE", description: "每5天食用1颗，不需要每天记着补充。简单、方便，更容易长期坚持。", metric: <><strong>5</strong><span>DAYS</span><i></i><strong>1</strong><span>PIECE</span></> },
  { number: "03", title: <>一盒14颗，<br/>约70天的日常保养。</>, highlight: "14 PIECES · ≈ 70 DAYS", description: "按照5天1颗的建议食用方式，一盒即可食用约70天。", metric: <><strong>70</strong><span>DAYS</span></> },
  { number: "04", title: <>不只是有心，<br/>关键是还要有力。</>, highlight: "ENERGY · STAMINA · VITALITY", description: "精神、体力、耐力、男性活力——男人真正需要的，从来不是只照顾一个方向。", emphasis: "Better Man 从整体状态出发，让你白天有精神，晚上有状态，关键时刻更有底气。" },
];
function Trust() { return <section id="why-better-man" className="section why-better"><div className="container"><div className="why-heading"><div><span>WHY BETTER MAN</span><strong>为什么选择 Better Man</strong></div><div><h2>男人要的，<br/><em>不只是那一下。</em><br/><b>是整个人的状态回来。</b></h2><p>真正影响男人表现的，从来不只是某一个瞬间。<br/>精神、体力、耐力、男性活力和整体状态，每一个都重要。</p><strong>Better Man，从男人真正关心的状态出发。</strong></div></div><div className="why-reasons">{whyReasons.map((item) => <article key={item.number} className={`why-reason why-reason-${item.number}`}><span className="why-number">{item.number}</span>{item.metric && <div className="why-metric" aria-hidden="true">{item.metric}</div>}<div className="why-reason-copy"><p>{item.highlight}</p><h3>{item.title}</h3><div>{item.description}</div>{item.emphasis && <strong className="why-reason-emphasis">{item.emphasis}</strong>}</div></article>)}</div></div></section>; }
const faqs = [
  { question: "Better Man 怎么吃？", paragraphs: ["建议每5天食用1颗，按照规律持续补充即可。", "不需要天天吃，也不需要等到有需要的时候才想起食用。"] },
  { question: "一盒有多少颗？可以吃多久？", paragraphs: ["每盒共有14颗。", "按照每5天1颗的建议食用方式，一盒约可食用70天。"] },
  { question: "Better Man 主要有什么成分？", paragraphs: ["Better Man 结合4种配方成分，以红东革阿里与黑玛卡作为核心，搭配锌与罗汉果，从男性日常精神、体力、耐力与活力等方向进行补充。"] },
  { question: "Better Man 主要适合哪些男性？", paragraphs: ["适合开始感觉精神、体力、耐力或男性状态不如以前，希望通过日常调理维持整体状态的成年男性。"] },
  { question: "一般多久会感觉到变化？", paragraphs: ["每个人的身体状态、生活习惯和吸收情况不同，因此实际感受时间也会有所不同。", "Better Man 更强调规律补充与持续调理，而不是把它当成只追求一次即时感觉的产品。"] },
  { question: "Better Man 是有需要的时候才吃吗？", paragraphs: ["不是。", "Better Man 的理念是把男性状态放在平时照顾，而不是等到真正需要的时候才开始。", "按照建议每5天1颗规律补充，让日常保养变得更简单。"] },
  { question: "第一次吃，建议先买几盒？", paragraphs: ["如果是第一次接触 Better Man，可以先根据自己的需求选择适合的配套。", "如果不确定应该怎么选择，可以直接通过 WhatsApp 联系我们，我们会根据你的情况提供产品与食用方式说明。"] },
  { question: "食用 Better Man 需要注意什么？", paragraphs: ["请按照建议食用方式使用，不需要自行增加食用量。", "如果正在服用药物、正在接受治疗，或本身有特殊健康状况，建议食用前先咨询医生或合格医疗专业人士。"] },
  { question: "Better Man 多少钱？", paragraphs: ["Better Man 不同地区及活动期间的配套可能有所不同。", "点击 WhatsApp 联系我们，即可查看目前最新配套与优惠。"], link: "查看目前优惠 →" },
  { question: "怎样下单？", paragraphs: ["点击网站任何一个绿色 WhatsApp 按钮，即可进入一对一咨询与下单。", "告诉我们你所在的地区，我们会提供目前可选择的配套、价格及下单方式。"], link: "WhatsApp 立即咨询 ↗", button: true },
];
function FAQ() { return <section id="faq" className="section section-cream"><div className="container faq-layout"><div><SectionHeading eyebrow="10 / FAQ" title="你可能还想了解" desc="有关 Better Man 的常见问题，都在这里。"/><WaButton>还有疑问？WhatsApp 咨询</WaButton></div><div className="faq-list">{faqs.map((item,i) => <details key={item.question}><summary><span className="faq-number">{String(i+1).padStart(2,"0")}</span><strong>{item.question}</strong><ChevronDown size={20}/></summary><div className="faq-answer"><div>{item.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{item.link && <a className={item.button ? "faq-answer-button" : "faq-answer-link"} href={whatsappHref()} target="_blank" rel="noopener noreferrer">{item.link}</a>}</div></div></details>)}</div></div></section>; }
function FinalCTA() { return <section className="final-cta"><div className="container final-inner"><Eyebrow>BETTER MAN</Eyebrow><h2>有些状态，<br/><em>拖着不会自己变回以前。</em></h2><p>如果你已经发现精神、体力、耐力，甚至男人状态开始不如以前，与其继续拖，不如从现在开始认真照顾自己的状态。</p><div className="final-slogan">Better Man，有心又有力，随时都 Ready。</div><WaButton light>WhatsApp 私下了解</WaButton><small>了解产品、吃法及目前配套。</small></div></section>; }
function Footer() { return <footer className="footer"><div className="container"><div className="footer-main"><div><a className="brand footer-brand" href="#home" aria-label="Better Man 首页"><BrandLogo/></a></div><nav aria-label="页脚导航"><a href="#benefits">产品介绍</a><a href="#ingredients">4大成分</a><a href="#how-to-use">食用方式</a><a href="#reviews">顾客反馈</a><a href="#faq">FAQ</a><a href="/privacy/">Privacy Policy</a><a href="/terms/">Terms</a></nav></div><div className="footer-bottom"><p>本网站提供的资料仅供一般产品资讯与日常保健参考，并非医疗建议、诊断或治疗用途。如有健康相关疑问，请咨询专业医疗人员。</p><span>© {new Date().getFullYear()} Better Man. All rights reserved.</span></div></div></footer>; }
function FloatingWhatsApp() { return <a className="floating-wa" href={whatsappHref()} target="_blank" rel="noopener noreferrer" aria-label="通过 WhatsApp 咨询 Better Man"><MessageCircle size={23} fill="currentColor"/><span>WhatsApp 咨询</span></a>; }
export function Site({ productAvailable, photos, videos }: { productAvailable: boolean; photos: PhotoReview[]; videos: VideoReview[] }) { return <><Header/><main><Hero/><Problems/><EmotionalTransition/><Benefits productAvailable={productAvailable}/><Ingredients/><Philosophy/><HowToUse/><AgeGroups/><CustomerReviews photos={photos} videos={videos}/><Trust/><FAQ/><FinalCTA/></main><Footer/><FloatingWhatsApp/></>; }






